name: goldenity_pos_native
description: Goldenity POS V2 Native - Tablet F&B
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4

  json_annotation: ^4.9.0
  uuid: ^4.5.1
  qr_flutter: ^4.1.0
  intl: ^0.20.2

  http: ^1.2.2
  crypto: ^3.0.3

  esc_pos_utils: ^1.1.0

  flutter_pos_printer_platform_image_3: ^1.2.4
  image: ^3.3.0
  local_notifier: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
